### ISSUE TITLE
[优化架构] 重新设计分栏 & 书面语化 & 添加步骤+图片指导

### ISSUE THREAD

**Issue by sudoskys** [sudoskys/Root#12]
- [x] 重新梳理文章
- [x] 设计分页
- [x] 工具应该在附录，使用超链接建立联系
- [x] 重新设计分栏 
- [x] 书面语化  
- [ ] 添加步骤+图片指导

不肯定的内容不要写

**Comment by sudoskys** [comment]
刷机方法应该分页

**Comment by wuhang2003** [comment]
可以适当考虑一下文案里中英文混写的优化
关于这一点 [AutoCorrect](https://github.com/huacnlee/autocorrect) 可以帮助完成大部分的修改操作

**Comment by sudoskys** [comment]
https://github.com/shibing624/pycorrector
