### ISSUE TITLE
内容修改建议

### ISSUE THREAD

**Issue by hk56184172** [sudoskys/Root#13]
root、刷rec、rom通用教程/解锁BootLoader/开始  
这个目录是否有必要说明一下 大部分机型不具备解锁bootloader锁的条件，并且列举出一些常见的可以解锁的品牌和不可以解锁的品牌

**Comment by hk56184172** [comment]
甚至将一些可以解锁品牌的解锁方法浅写一下

**Comment by sudoskys** [comment]
是的,但是这需要类似问卷的工具来收集信息

**Comment by nanbeiduoqilu** [comment]
![1](https://user-images.githubusercontent.com/92634997/200988227-ee4e8816-0f0b-4e20-ae0a-e59fc09f711a.png)
请问一下这里是不是应该是与其回答你的啥问题，不如***，哈哈哈

**Comment by nanbeiduoqilu** [comment]
![1](https://user-images.githubusercontent.com/92634997/200988311-13002b3c-54f2-439a-8c1e-31e64b21ce93.png)
q'w请问这里是不是应该是回答你的傻问题

**Comment by sudoskys** [comment]
> ![1](https://user-images.githubusercontent.com/92634997/200988311-13002b3c-54f2-439a-8c1e-31e64b21ce93.png) q'w请问这里是不是应该是回答你的傻问题

这里不是我亲笔写的，orz,我改一下

**Comment by sudoskys** [comment]
<img width="505" alt="fastboot" src="https://user-images.githubusercontent.com/75739606/210176260-9ce22fb7-e8b3-4a36-b3ba-23c181b27f0e.png">

**Comment by Molyuu** [comment]
正在写正在写.png
