### ISSUE TITLE
issue: docs/index.md与docs/optimize.md文中引用图片url失效

### ISSUE THREAD

**Issue by Dedicatus5457** [sudoskys/Root#15]
rt,
https://s1.328888.xyz/2022/08/13/TG 与 https://s1.328888.xyz/2022/08/13/TGDNR.png 图床 url 失效
![image](https://user-images.githubusercontent.com/78254776/205436542-2f8f9f62-59a1-4378-9a1a-402f37e60d83.png)
![image](https://user-images.githubusercontent.com/78254776/205436546-a864cdd0-7b10-4c9e-825e-2960be0f8ba2.png)
FaP.png

**Comment by sudoskys** [comment]
啊这

**Comment by sudoskys** [comment]
fixed
